// Return the selected date and close the popup
function selectDate(year, month, day, dateStr) {
    var popup = scada.popupLocator.getPopup();
    if (popup) {
        popup.closeDropdown(window, true, { date: new Date(year, month - 1, day), dateStr: dateStr });
    }
}

$(document).ready(function () {
    // remove default calendar colors generated by ASP.NET
    $("#frmCalendar *").css({
        "background-color": "",
        "color": ""
    });
});