#!/bin/sh
### BEGIN INIT INFO
# Provides:          scadaserver
# Required-Start:    $remote_fs $network $time
# Required-Stop:     $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: SCADA-Server daemon
# X-Start-Before:    scadacomm
# X-Stop-After:      scadacomm
### END INIT INFO

# This script was modified and adapted for Rapid SCADA by Nikita Yakuntsev

SERVICE_NAME=SCADA-Server
EXE_DIR=/etc/scada/ScadaServer/
EXE_NAME=ScadaServerMono.exe
STOP_FILE_PATH=Cmd/serverstop
PID_FILE_PATH=/tmp/scadaserver
MAX_DELAY=12

do_start()
{
    if [ ! -f $PID_FILE_PATH ]; then
        echo "Starting $SERVICE_NAME ..."
        cd $EXE_DIR
        mono $EXE_NAME & echo $! > $PID_FILE_PATH
        if [ -f $STOP_FILE_PATH ]; then
            rm  $STOP_FILE_PATH
        fi

        echo "$SERVICE_NAME is started"
    else
        echo "$SERVICE_NAME is already running"
    fi
}

do_stop()
{
    if [ -f $PID_FILE_PATH ]; then
        echo "Terminating $SERVICE_NAME ..."
        PID = $(cat $PID_FILE_PATH);
        cd $EXE_DIR
        touch $STOP_FILE_PATH
        for (( i = 0; i < MAX_DELAY; i++ )) do
            sleep 1
            if [ ! -f $STOP_FILE_PATH ]; then
                break;
            fi
        done

        kill $PID;
        echo "$SERVICE_NAME is stopped"
        rm $PID_FILE_PATH
    else
        echo "$SERVICE_NAME is not running"
    fi
}

case $1 in
    start)
        do_start
    ;;
    stop)
        do_stop
    ;;
    restart)
        do_stop
        do_start
    ;;
esac 